### PR TITLE
make build work on mingw-w64

### PR DESCRIPTION
**Pull request by asanoic**
also we get benefit on Linux cross-compiling to Windows

### CODE REVIEW

**Comment by magiblot** [comment]
Hi Asano! Cool! Thank you very much.

I'll review the changes and write some comments.

Also, what steps do you follow to build this with mingw64? I would like to add them to the README.

**Comment by asanoic** [comment]
sure thing

**Comment by asanoic** [comment]
BTW, do you have plan to make `CMakeLists.txt` use modern target based, I can make another PR to do this. It will make other guys easy to use this library. ( just use `add_subdirectory` ). latest Debian(buster) system software repositories cmake version is 3.13.0 ( latest cmake is 3.18.4) could we make it minimum required?

**Comment by magiblot** [comment]
I would be very grateful if you could do that!

**Comment by asanoic** [comment]
I am about do some regression tests on Linux, and just found that you got the issue about `#elseif` COOL!

**Comment by magiblot** [comment]
I have tried to build this with Mingw64, and I've had no issue using the Microsoft C Runtime, which provides the functions that had been giving us trouble (`getcwd`, `chdir`, etc.). These functions didn't work at first because the compatibility headers used `#ifdef _MSC_VER` instead of a more generic `#ifdef _WIN32`. Is there a particular reason why you didn't use the MS C Runtime? Otherwise, I'll post a few more changes so that you can try them.

**Comment by asanoic** [comment]
> I have tried to build this with Mingw64, and I've had no issue using the Microsoft C Runtime, which provides the functions that had been giving us trouble (`getcwd`, `chdir`, etc.). These functions didn't work at first because the compatibility headers used `#ifdef _MSC_VER` instead of a more generic `#ifdef _WIN32`. Is there a particular reason why you didn't use the MS C Runtime? Otherwise, I'll post a few more changes so that you can try them.

yep, I will definitely try it tomorrow morning when I switch to Windows machine. I just found that CMake on Windows if you want to use gcc to build, you have to use `cmake . -G "MinGW Makefiles"` (case sensitive). why I did not add it because I always use my customized CMake. please change and rerun your Travis CI , that is answer your questions why I prefer Windows API rather than MSVC C Runtime, because some MSVC C functions might not be available on MinGW-w64.

**Comment by asanoic** [comment]
after this pull request merged I will working on CMakeLists.txt for using better modern target based commands.

**Comment by asanoic** [comment]
job 3.9 actually uses MSVC to build, please check the job log at https://travis-ci.com/github/magiblot/tvision/jobs/429312966

**Comment by magiblot** [comment]
> I prefer Windows API rather than MSVC C Runtime, because some MSVC C functions might not be available on MinGW-w64

Okay. Well, it works fine here. I'll wait to see if it also works well for you, and if it does then I suggest to keep using them, because it really makes things a lot easier. The implementation of some of these functions, such as `setdisk`, is not trivial.

> after this pull request merged I will work on CMakeLists.txt for using better modern target based commands.

I really appreciate this!

> job 3.9 actually uses MSVC to build, please check the job log at https://travis-ci.com/github/magiblot/tvision/jobs/429312966

Yes, I know. Actually, it was not me who prepared the Travis environment, it was another contribution by the community. When I enabled it today, I was more interested in testing build regressions for other platforms. I don't know how Travis works very well either, so I have not added a MinGW environment yet. But I seem to be running out of Travis credits quite fast, so I'll probably have to switch to another CI service.

**Comment by asanoic** [comment]
it works on my local! and I do a small tweak to remove a compiler warning. I also tried to cherry-pick and change `.travis.yml`, but I failed because I am not very familiar with it, have to force push to back. I think we are good to go.

**Comment by magiblot** [comment]
I think what you wanted to do was a rebase so that the pull request commits would have been reapplied on top of `magiblot/master`, but this can be a bit complex, considering that the commits were in another repository.

> and I did a small tweak to remove a compiler warning.

Okay. Also: even if you reverted the usage of `auto` because Clang complained, don't forget that the code under the `source/tvision` directory is also expected to build on the pre-C++98 compiler Borland C++, so `auto` wouldn't have worked there either.

I also think this is ready to be merged. If you don't mind, I will squash some of the commits.

Thank you!

**Comment by magiblot** [comment]
Okay, I won't forget to add it.

**Pull request closed without merging**
