### PR TITLE
use modern target based commands on CMakeLists.txt

### PR DESCRIPTION
**Pull request by asanoic**
almost rewrite everything, and because target based commands are location independent, so I just used default location to put all generate lib and binaries. when run `cmake --install .` it will install correct place.

### CODE REVIEW

**Comment by asanoic** [comment]
it passed my local (Windows/ GCC /MinGW-w64), I will try it on Linux soon.

**Comment by asanoic** [comment]
if I set `HAVE_NCURSES` and `HAVE_GPM` private, it won't reuse the pre-compiled header

**Comment by magiblot** [comment]
> if I set HAVE_NCURSES and HAVE_GPM private, it won't reuse the pre-compiled header

This is alright. In the original CMakeLists, this was handled by generating a separate pre-compiled header for the applications.

**Comment by asanoic** [comment]
> 
> 
> > if I set HAVE_NCURSES and HAVE_GPM private, it won't reuse the pre-compiled header
> 
> This is alright. In the original CMakeLists, this was handled by generating a separate pre-compiled header for the applications.

let me change it.

**Comment by magiblot** [comment]
Thank you! The build issue on Apple should be fixed, but Travis seems to be picking the commit wrong.

I will do some cosmetic changes and see if it passes the build test.

**Comment by magiblot** [comment]
Could the issue be a missing '/'?:

```diff
-       "${CMAKE_CURRENT_LIST_DIR}include/tvision/compat/malloc")
+       "${CMAKE_CURRENT_LIST_DIR}/include/tvision/compat/malloc")
```

**Comment by magiblot** [comment]
```cmake
if (MSVC)
    target_compile_options(${CMAKE_PROJECT_NAME} PUBLIC
        /wd4068
        /wd4146
        /wd4166
        /wd4244
        /wd4250
        /wd4267
        /wd4996
        /permissive-
        /Zc:__cplusplus)
else()
```
`MSVC` does not always mean "MSVC compiler". For example, you can open this project in Visual Studio and pick Clang. With `if (MSVC)`, Clang does not get the required flags and prints warnings like crazy. So I think the previous `if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")` was right. I can change this myself.

**Comment by asanoic** [comment]
> 
> 
> Could the issue be a missing '/'?:
> 
> ```diff
> -       "${CMAKE_CURRENT_LIST_DIR}include/tvision/compat/malloc")
> +       "${CMAKE_CURRENT_LIST_DIR}/include/tvision/compat/malloc")
> ```

just saw your message, that needed really sharp eyes, LOL

**Comment by asanoic** [comment]
> 
> 
> ```cmake
> if (MSVC)
>     target_compile_options(${CMAKE_PROJECT_NAME} PUBLIC
>         /wd4068
>         /wd4146
>         /wd4166
>         /wd4244
>         /wd4250
>         /wd4267
>         /wd4996
>         /permissive-
>         /Zc:__cplusplus)
> else()
> ```
> 
> `MSVC` does not always mean "MSVC compiler". For example, you can open this project in Visual Studio and pick Clang. With `if (MSVC)`, Clang does not get the required flags and prints warnings like crazy. So I think the previous `if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")` was right. I can change this myself.

maybe we can use `CMAKE_GENERATOR_TOOLSET`, please check https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html, but I don't know the Borland C++'s compiler options.

**Comment by magiblot** [comment]
```cmake
        if (NOT MSVC AND NOT APPLE AND NOT BORLAND) ## which means GCC/MINGW
            target_compile_options(${app} PRIVATE -Wno-stringop-truncation)
        endif()
```
I have to disagree with this. If we are interested in GCC/MINGW, what sense does it make to check for every single other compiler? Additionally, this flag only has to be applied on the `tvdir` application, because I know the code causing this warning is OK. But in another application it could be an actual bug and the warning should not be disabled by default.

So, I think the original `if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")` is alright, because it also detects MinGW. But I actually don't know if there's something wrong with checking compilers that way. Is there a specific reason why the `"${CMAKE_CXX_COMPILER_ID}"` checks were removed?

> maybe we can use CMAKE_GENERATOR_TOOLSET, please check https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html

Thanks! I will take a look at it,

> but I don't know the Borland C++'s compiler options.

Borland C++ is never used with CMake. Build with Borland C++ is done using separate Makefiles compatible with Borland's custom Make utility.

**Comment by asanoic** [comment]
You are correct. And I agree with you. Why I did that is that I was trying to reduce hard-coded const/variable in CMakeLists.txt

**Comment by magiblot** [comment]
> Why I did that is that I was trying to reduce hard-coded const/variable in CMakeLists.txt

Reducing hardcoded things is always good, so thank you for trying to improve it. If there was a `GNU` variable that meant just what was needed I would have used it, but there isn't one.

So, I'll post a commit changing some of these things.

**Comment by magiblot** [comment]
I have changed the style of the multiline function calls. I hope you are fine with that.

**Comment by magiblot** [comment]
Would there be any issue in downgrading the `cmake_minimum_required` again? It looks like we are not using any newer feature.

**Review by asanoic — COMMENTED** [review]
we should make malloc includes dir to PUBLIC. because once ${app} needs malloc, my next new project using TVision will need too..

**Comment by asanoic** [comment]
> Would there be any issue in downgrading the `cmake_minimum_required` again? It looks like we are not using any newer feature.

Debian is well known as stability and pretty old packages. so all my projects minimum version always follow latest Debian package version. if you want to let even older version of cmake work, no harmful to switch back.

**Comment by asanoic** [comment]
> we should make malloc includes dir to PUBLIC. because once ${app} needs malloc, my next new project using TVision will need too..

I think after these changes your `turbo` project cmake file just need add two lines to link with `tvision` (as git submodule)
```
add_subdirectory(tvision)
target_link_libraries(turbo tvision)
```

**Comment by magiblot** [comment]
Mhm... the malloc directory is there only for legacy code using `<malloc.h>`, which platform-dependent. The reason why this directory exists is because the alternative would be to add several `#ifdef` in every source file relying on this header, which goes against simplicity. The same logic applies to all the other headers under the `tvision/compat` directory. The compatibility headers are just a means to allow legacy code to compile out-of-the-box, just by adding the necessary include directories.

I feel like by making it PUBLIC we are enforcing it on any projects using Turbo Vision. Or am I not understanding the meaning of PUBLIC/PRIVATE right?

New projects should of course not use `<malloc.h>`, but `<cstdlib>`, which provides the `malloc` function. So under normal circumstances, new applications will never include `<malloc.h>`. Am I missing something?

> I think after these changes your turbo project cmake file just need add two lines to link with tvision (as git submodule)

Yes, this should make Turbo's CMakeLists a lot simpler. Thank you!

**Comment by magiblot** [comment]
When I do `add_subdirectory` from Turbo's CMakeLists, I get errors because `${CMAKE_PROJECT_NAME}` in `tvision/CMakeLists.txt` gets replaced with `turbo` instead of `tvision`. Either I'm doing something wrong, or we'll have to go back to not using `CMAKE_PROJECT_NAME`.

**Comment by magiblot** [comment]
In the end I replaced `CMAKE_PROJECT_NAME` again with `tvision`. I'm sorry to have reverted your changes, but I have seen that using the target name directly is also common in other projects, so I thought there'd be nothing bad to it.

**Comment by asanoic** [comment]
> In the end I replaced `CMAKE_PROJECT_NAME` again with `tvision`. I'm sorry to have reverted your changes, but I have seen that using the target name directly is also common in other projects, so I thought there'd be nothing bad to it.

You might need change ‘CMAKE_PROJECT_NAME’ to ‘PROJECT…NAME’

**Comment by magiblot** [comment]
You read my mind, I was about to revert the changes as well :)

**Comment by asanoic** [comment]
When I worked on this, I found -O2 option is added to compiler, so I added following lines to cmake
```
if (NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()
```
actually it works, the link you shown is obsoleted. checking way is easy, just add `set(CMAKE_VERBOSE_MAKEFILE ON)` to `CMakeLists.txt` for compilation details, but in the `CMakeCache.txt`, it still shows emtpy. because this changes at runtime.

when you run `cmake . -DCMAKE_BUILD_TYPE=Debug` is still build as debug mode, because the `CMAKE_BUILD_TYPE` is not empty now. it only builds as Release mode when `CMAKE_BUILD_TYPE` is not provided, like `cmake .`.

**Comment by asanoic** [comment]
I also change `README.md` and `.travis.yml` because we use cmake default output path. please check.
we might need add a guide for how to use this library when using cmake build after your `turbo` works :)

**Comment by asanoic** [comment]
just checked MinGW-w64 build `ZERO error ZERO warning`  😆

**Comment by magiblot** [comment]
Thank you! I'm still doing tests with Turbo.

**Comment by magiblot** [comment]
> I did not re-add it, you can decide whether bring it back or not.

I could add it in the future, but for the moment I have changed the build examples in the README so that they show CMAKE_BUILD_TYPE being set from the command line.

I have also added a brief explanation of how to use Turbo Vision as a CMake subproject. Do you think something is missing? Otherwise, I think this is ready to merge.

**Comment by magiblot** [comment]
Merged! Thank you very much!

**Pull request closed without merging**
